version: '3.8'

services:
  db:
    container_name: '${POSTGRES_DOCKER_NAME:-postgres-main}'
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdataVolume:/var/lib/postgresql/data

volumes:
  pgdataVolume:
