env:
  dev:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    STAGE: 'DEV'
    ENV: 'dev'
    DATABASE_URL: ${env:DATABASE_URL}
    DATABASE_URL_QA: ${env:DATABASE_URL_QA}
    DATABASE_URL_PROD: ${env:DATABASE_URL_PROD}
    ORIGIN_DEV: ${env:ORIGIN_DEV}
    ORIGIN_QA: ${env:ORIGIN_QA}
    ORIGIN_PROD: ${env:ORIGIN_PROD}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_RESET: ${env:JWT_RESET}
    JWT_DEFAULT_EXPIRATION: ${env:JWT_DEFAULT_EXPIRATION}
    JWT_RESET_EXPIRATION: ${env:JWT_RESET_EXPIRATION}
    AMAZON_REGION: ${env:AMAZON_REGION}

  qa:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    STAGE: 'QA'
    ENV: 'qa'
    DATABASE_URL: ${env:DATABASE_URL_QA}
    ORIGIN_QA: ${env:ORIGIN_QA}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_RESET: ${env:JWT_RESET}
    JWT_DEFAULT_EXPIRATION: ${env:JWT_DEFAULT_EXPIRATION}
    JWT_RESET_EXPIRATION: ${env:JWT_RESET_EXPIRATION}
    AMAZON_REGION: ${env:AMAZON_REGION}

  prod:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    STAGE: 'PROD'
    ENV: 'prod'
    DATABASE_URL: ${env:DATABASE_URL_PROD}
    ORIGIN_PROD: ${env:ORIGIN_PROD}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_RESET: ${env:JWT_RESET}
    JWT_DEFAULT_EXPIRATION: ${env:JWT_DEFAULT_EXPIRATION}
    JWT_RESET_EXPIRATION: ${env:JWT_RESET_EXPIRATION}
    AMAZON_REGION: ${env:AMAZON_REGION}
